services:
  backend:
    build: ./backend

    ports:
      - "8000:8000"

    environment:
      OLLAMA_URL: ${OLLAMA_URL}
      MODEL_NAME: ${MODEL_NAME}

    depends_on:
      ollama:
        condition: service_started

    volumes:
      - chroma_data:/app/chroma_data

    restart: unless-stopped

  ollama:
    image: ollama/ollama

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped

volumes:
  chroma_data:
  ollama_data: